# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/browt/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-5708-LAPTOP-683OQKA0/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/browt/Documents/EE-CE Materials/VHDL Projects/scrolling_marquee/scrolling_marquee.cache/wt} [current_project]
set_property parent.project_path {C:/Users/browt/Documents/EE-CE Materials/VHDL Projects/scrolling_marquee/scrolling_marquee.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/browt/Documents/EE-CE Materials/VHDL Projects/scrolling_marquee/scrolling_marquee.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/browt/Documents/EE-CE Materials/VHDL Projects/VHDL Custom Module Directory/anode_selector.vhd}
  {C:/Users/browt/Documents/EE-CE Materials/VHDL Projects/scrolling_marquee/scrolling_marquee.srcs/sources_1/new/buffer_6_bit.vhd}
  {C:/Users/browt/Documents/EE-CE Materials/VHDL Projects/scrolling_marquee/scrolling_marquee.srcs/sources_1/new/char_sequence_decoder.vhd}
  {C:/Users/browt/Documents/EE-CE Materials/VHDL Projects/VHDL Custom Module Directory/count_up_and_delay.vhd}
  {C:/Users/browt/Documents/EE-CE Materials/VHDL Projects/VHDL Custom Module Directory/multiplexer_8_bit_4_to_1.vhd}
  {C:/Users/browt/Documents/EE-CE Materials/VHDL Projects/VHDL Custom Module Directory/multiplexer_seven_segment_display.vhd}
  {C:/Users/browt/Documents/EE-CE Materials/VHDL Projects/VHDL Custom Module Directory/seven_segment_decoder.vhd}
  {C:/Users/browt/Documents/EE-CE Materials/VHDL Projects/VHDL Custom Module Directory/two_bit_counter.vhd}
  {C:/Users/browt/Documents/EE-CE Materials/VHDL Projects/VHDL Custom Module Directory/var_clock_divider.vhd}
  {C:/Users/browt/Documents/EE-CE Materials/VHDL Projects/VHDL Custom Module Directory/var_clock_divider_2.vhd}
  {C:/Users/browt/Documents/EE-CE Materials/VHDL Projects/scrolling_marquee/scrolling_marquee.srcs/sources_1/new/top_level.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/browt/Documents/EE-CE Materials/VHDL Projects/scrolling_marquee/scrolling_marquee.srcs/constrs_1/new/constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/browt/Documents/EE-CE Materials/VHDL Projects/scrolling_marquee/scrolling_marquee.srcs/constrs_1/new/constraints.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top_level -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_level.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
